### ISSUE TITLE
kubeconfig

### ISSUE THREAD

**Issue by pydevops** [upmc-enterprises/kubeadm-aws#4]
It would be super handy to generate kubeconfig so that kubectl can be used to manage new manifest.

**Comment by anuaimi** [comment]
I took a quick look at that.  Very easy to open port 8080 on the master VM.  But currently the API is only listening on localhost.  Need to figure out how to have listen on all interfaces

**Comment by stevesloka** [comment]
The current docs say that you need to scp the file to your local workstation. I'll look into the ports, and make sure those are updated correctly, but I think you'll still need the certs to auth to the api server, but let me check on that. 

```
There is not yet an easy way to generate a kubeconfig file which can be used to authenticate to the cluster remotely with kubectl on, for example, your workstation.

Workaround: copy the kubelet’s kubeconfig from the master: use scp root@<master>:/etc/kubernetes/admin.conf . and then e.g. kubectl --kubeconfig ./admin.conf get nodes from your workstation.
```

**Comment by pydevops** [comment]
close it.
