### ISSUE TITLE
license for project should be more 'open source' friendly

### ISSUE THREAD

**Issue by anuaimi** [upmc-enterprises/kubeadm-aws#6]
Right now the license with this project says that all code and any changes are owned by UPMC.  This discourages people contributing to the project.  It would be nice if it used Apache instead

**Comment by stevesloka** [comment]
The current license basically lets you do whatever you want, just as long as you don't blame my company for anything that results from using the code. I'll ask if we could switch out the license, but this was the one they asked I use with OpenSource.  When I hear back I can update this issue.
